### PR TITLE
Potential appendix about iregexp tool

### PR DESCRIPTION
**Pull request by cabo**
(In response to Rob Wilton's IESG comment.)

### CODE REVIEW

**Review by timbray — COMMENTED** [review]
I have issues with this. RFCs are immutable, as close as anything on the Internet can be. Software tools are fragile, subject to bitrot, forks, human sabotage, etc etc etc.  It feels deeply weird to have a particular software tool called out in an RFC.  Or am I just out of date, has this become a common practice?

**Comment by cabo** [comment]
I mentioned
https://www.rfc-editor.org/rfc/rfc8610#appendix-F
https://www.rfc-editor.org/rfc/rfc9052#appendix-C
There is a tradeoff between providing help to earlier implementers quickly and staying up-to-date for decades.
For 8610 and 9052, we made the decision that the former was worth it.
9052 even is at Internet Standard level...
But we should make the decision consciously here as well.

**Comment by glyn** [comment]
I'd be concerned about RFCs containing ephemeral information such as links to implementations, test suites, etc. Even the likes of github.com may not persist indefinitely. Then's there's the bitrot etc. mentioned above.

I wonder if a different solution has been considered. Why not place such information on a page at (datatracker.)ietf.org which could then be edited over time and then link to that page from the spec?

**Comment by cabo** [comment]
The problem with such a page being an IETF product is that we'd need a process for maintaining it, with all the conflict resolution mechanisms (appeals, escalation, ...) that such a process needs.
Pointing to an external resource leaves no doubt that this page is not the result of an IETF consensus process.

This is not the first time we have thought about that.
[RFC 7942](https://www.rfc-editor.org/rfc/rfc7942) describes an Implementation Status section that is intended to be removed before publication.  This is appropriate for a list of actual implementations, which is likely to grow and mature over the first few years of an RFC being available, so it gets outdated quickly.

The two appendices I'm citing from RFC 8610 and RFC 9052 (was in its predecessor RFC 8152 as well) are pointing to tools that have specifically been written to support the development and use of the standard.  RFC 8949 has a resource (cbor.io) that lists actual implementations; this is a bit harder to maintain after 10 years of implementation activity, but it is still alive.  RFC 8949 also has cbor.me that is a playground for converting instances between interchange and diagnostic form.  Both are not referenced from the standard.

Given that there are multiple valid ways this has been done in the past, I'd prefer not to discuss this in general terms (as if this were something new for the IETF that we need to approach in a trail-blazing way, setting the example for others to follow), but to look at the specific outcome we might be able to attain by including (or not including) such an appendix for this particular specification.

**Comment by timbray** [comment]
At this point, my position is that the proposed appendix does not add sufficient value, and that the ABNF is a sufficient basis for building a checker.

**Comment by cabo** [comment]
Thank you.  Closing this PR now.

**Pull request closed without merging**
